# Generated by Django 4.0.8 on 2022-12-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
            },
        ),
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.courier', verbose_name='courier')),
            ],
            options={
                'verbose_name': 'weeklyincome',
                'verbose_name_plural': 'weeklyincomes',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Processed')])),
                ('type', models.IntegerField(choices=[(0, 'Trip'), (1, 'Reward'), (2, 'Punishment')])),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.courier', verbose_name='courier')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.courier', verbose_name='courier')),
            ],
            options={
                'verbose_name': 'DailyIncome',
                'verbose_name_plural': 'DailyIncomes',
            },
        ),
    ]
