# Generated by Django 4.0.8 on 2022-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyincome",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
    ]
