# Generated by Django 4.0.8 on 2022-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_dailyincome_date_alter_weeklyincome_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyincome',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Processed')], default=0),
            preserve_default=False,
        ),
    ]
