# Generated by Django 4.0.8 on 2022-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_dailyincome_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='weeklyincome',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AddConstraint(
            model_name='dailyincome',
            constraint=models.UniqueConstraint(fields=('date', 'courier'), name='courier_date_unique_together_daily_income'),
        ),
        migrations.AddConstraint(
            model_name='weeklyincome',
            constraint=models.UniqueConstraint(fields=('date', 'courier'), name='courier_date_unique_together_weekly_income'),
        ),
    ]
